name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }} # Use secret (https://developer.github.com/actions/managing-workflows/storing-secrets/)
    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: |
          ./deploy/deployment.yml
        images: |
          ghcr.io/veremchukvv/plantbook/restapi:latest