name: CI_CD
on:
  push:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38

  postman:
    needs: golangci
    name: postman
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: full deploy
        uses: matt-ball/newman-action@master
        with:
          collection: ./scripts/postman/plantbook.postman_collection.json
          envVar: baseURL=plantbook.icu