name: CI_CD
on:
  push:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38

  push_to_registry:
    needs: golangci
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./build/restapi/Dockerfile
          tags: ghcr.io/veremchukvv/plantbook/restapi:latest
          build-args: |
            BUILD_NUMBER=${{ github.sha }}
            GITSHA=${{ github.build.nummer }}
  deploy:
    needs: push_to_registry
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: kube login
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: precheck
        run: |
          OUTPUT=$(kubectl rollout status deployment plantbook 2>&1) && echo "::set-output name=OUTPUT::$OUTPUT"
        continue-on-error: true
        id: status
      - name: full deploy
        if: steps.status.outputs.OUTPUT != 'deployment "plantbook" successfully rolled out'
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'g1-vladimir'
          manifests: |
            ./deploy/deployment.yml
          images: |
            ghcr.io/veremchukvv/plantbook/restapi:latest
      - name: re-roll
        if: steps.status.outputs.OUTPUT == 'deployment "plantbook" successfully rolled out'
        run: |
          kubectl delete po -l app=plantbook