name: TG-notif
on:
  pull_request:
    branches:
      - main
jobs:
  notif:
    name: notif
    runs-on: ubuntu-latest
    steps:
      - name: notif
      - uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TG_chat }}
          token: ${{ secrets.TG_token }}
          message: |
            The ${{ github.event_name }} HAPPEND!