name: TG-notif
on:
  pull_request:
    branches:
      - main
jobs:
  notif:
    name: notif
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        name: notif
        with:
          to: ${{ secrets.TG_chat }}
          token: ${{ secrets.TG_token }}
          message: |
            User: ${{ github.actor }} created new ${{ github.event_name }} -- ${{ github.job }} from branch ${{ github.head_ref }}