name: TG-notif
on:
  pull_request:
    branches:
      - main
jobs:
  notif:
    name: notif
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        name: notif
        with:
          to: ${{ secrets.TG_chat }}
          token: ${{ secrets.TG_token }}
          format: markdown
          message: |
            User: **${{ github.actor }}** created new PR [#${{ github.event.number }}](${{ github.event.pull_request.html_url }}) from branch: **${{ github.head_ref }}**